# Generated by Django 5.2.5 on 2026-04-21 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_types',
            fields=[
                ('loantype_id', models.AutoField(primary_key=True, serialize=False)),
                ('loantype_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('FName', models.CharField(max_length=100)),
                ('MName', models.CharField(max_length=100)),
                ('LName', models.CharField(max_length=100)),
                ('Phonenumber', models.CharField(max_length=15)),
                ('Usertype', models.CharField(choices=[('admin', 'Admin'), ('applicant', 'Applicant')], max_length=50)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.CreateModel(
            name='loanapplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loantype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loan_types')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='loan_documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='loan_documents/')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='payment_schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('payment_status', models.CharField(max_length=20)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loanapplication')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
